#!/usr/bin/env python3
import random
import os

# setting our random hostname
HOSTNAME = "android-%02x%02x%02x%02x%02x%02x%02x%02x" % (
    random.randint(0, 255),
    random.randint(0, 255),
    random.randint(0, 255),
    random.randint(0, 255),
    random.randint(0, 255),
    random.randint(0, 255),
    random.randint(0, 255),
    random.randint(0, 255),
    )

# system call to execute the commands
if os.sys.platform == "darwin":
    # Mac OS
    # ComputerName   The user-friendly name for the system.
    # LocalHostName  The local (Bonjour) host name.
    # HostName       The name associated with hostname(1) and gethostname(3).

    os.system("sudo scutil --set HostName " + HOSTNAME)
    os.system("sudo scutil --set ComputerName " + HOSTNAME)
    os.system("sudo scutil --set LocalHostName " + HOSTNAME)
elif os.sys.platform == "linux":
    # Linux
    os.system("sudo hostname " + HOSTNAME)
elif os.sys.platform == "win32":
    # Windows
    os.system(
        "wmic computersystem where name=\"%COMPUTERNAME%\" call rename name=\"" + HOSTNAME + "\""
        )

# inform the user about your new hostname
print("your new hostname is: " + HOSTNAME)
